-- Fixes a gap discovered while testing profiles.global_role's column-privilege
-- restriction: this Supabase CLI version does NOT auto-grant base table access to
-- authenticated/anon for newly created tables (see config.toml's api.auto_expose_new_tables
-- comment) — only REFERENCES/TRIGGER/TRUNCATE exist by default. Every RLS policy in
-- 20260812093200_rls_policies.sql has therefore been unreachable via PostgREST from
-- the start: RLS restricts *rows* you're privileged to see, but the base GRANT
-- controls whether you can query the table at all.
--
-- This migration fixes it for `profiles` only. groups/group_members/restaurants/
-- decisions/invitations have the same gap and are deliberately left as-is: data
-- access for those now goes through the NestJS API (BE/api), which connects with
-- its own elevated role and enforces authorization in application code, bypassing
-- RLS/grants entirely. Grant them too if a future feature needs direct client
-- (PostgREST) access to one of those tables.
grant select on public.profiles to authenticated;
